# glm.deploy

Generates the source code of the scoring algorithm (predict) of a GLM object to C or JAVA to deploy/operationalize it outside R.

## Output options
In this initial version the output source codes available are C and Java.

## Link Function Compatibility
The link functions compatible are:
  - identity, 
  - probit
  - cloglog
  - log
  - sqrt
  - inverse
  - 1/mu^2
  - logit.

## Example

This is a basic example with the iris dataset to create a glm object and pass it to the two functions glm2c and glm2java:

```{r example}
## basic example code
  data(iris)
  iristest = iris
  iristest$Virginica = ifelse(iristest$Species == 'virginica', TRUE,FALSE)
  iristest$Species = NULL
  model <- glm(Virginica ~ ., family = binomial(logit), data=iristest)
  glm2c(model)
  glm2java(model)
```
This would create two files, each file with two predict functions one equivalent to the predict(type="response") and other equivalent to the predict(type="link").

`glm2c()` will create the c source code in the file "glm_virginica.c"

`glm2java()` will create the java source code "glm_virgnica_class.java"

## Author

Oscar J. Castro-Lopez, Ines F. Vega-Lopez
